// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// StoresColumns holds the columns for the "stores" table.
	StoresColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "is_used", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "store_id", Type: field.TypeString},
		{Name: "app_access_key", Type: field.TypeString},
	}
	// StoresTable holds the schema information for the "stores" table.
	StoresTable = &schema.Table{
		Name:       "stores",
		Columns:    StoresColumns,
		PrimaryKey: []*schema.Column{StoresColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "is_used", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString},
		{Name: "user_name", Type: field.TypeString},
		{Name: "birthday", Type: field.TypeString},
		{Name: "weight", Type: field.TypeFloat64},
		{Name: "type", Type: field.TypeString},
		{Name: "store_id", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// StoreUsersColumns holds the columns for the "store_users" table.
	StoreUsersColumns = []*schema.Column{
		{Name: "store_id", Type: field.TypeUint64},
		{Name: "user_id", Type: field.TypeUint64},
	}
	// StoreUsersTable holds the schema information for the "store_users" table.
	StoreUsersTable = &schema.Table{
		Name:       "store_users",
		Columns:    StoreUsersColumns,
		PrimaryKey: []*schema.Column{StoreUsersColumns[0], StoreUsersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "store_users_store_id",
				Columns:    []*schema.Column{StoreUsersColumns[0]},
				RefColumns: []*schema.Column{StoresColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "store_users_user_id",
				Columns:    []*schema.Column{StoreUsersColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		StoresTable,
		UsersTable,
		StoreUsersTable,
	}
)

func init() {
	StoreUsersTable.ForeignKeys[0].RefTable = StoresTable
	StoreUsersTable.ForeignKeys[1].RefTable = UsersTable
}
