// Code generated by ent, DO NOT EDIT.

package ent

import (
	"main/ent/schema"
	"main/ent/store"
	"main/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	storeMixin := schema.Store{}.Mixin()
	storeMixinFields0 := storeMixin[0].Fields()
	_ = storeMixinFields0
	storeMixinFields1 := storeMixin[1].Fields()
	_ = storeMixinFields1
	storeFields := schema.Store{}.Fields()
	_ = storeFields
	// storeDescIsUsed is the schema descriptor for is_used field.
	storeDescIsUsed := storeMixinFields0[0].Descriptor()
	// store.DefaultIsUsed holds the default value on creation for the is_used field.
	store.DefaultIsUsed = storeDescIsUsed.Default.(bool)
	// storeDescCreatedAt is the schema descriptor for created_at field.
	storeDescCreatedAt := storeMixinFields1[0].Descriptor()
	// store.DefaultCreatedAt holds the default value on creation for the created_at field.
	store.DefaultCreatedAt = storeDescCreatedAt.Default.(func() time.Time)
	// storeDescUpdatedAt is the schema descriptor for updated_at field.
	storeDescUpdatedAt := storeMixinFields1[1].Descriptor()
	// store.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	store.DefaultUpdatedAt = storeDescUpdatedAt.Default.(func() time.Time)
	// store.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	store.UpdateDefaultUpdatedAt = storeDescUpdatedAt.UpdateDefault.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescIsUsed is the schema descriptor for is_used field.
	userDescIsUsed := userMixinFields0[0].Descriptor()
	// user.DefaultIsUsed holds the default value on creation for the is_used field.
	user.DefaultIsUsed = userDescIsUsed.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields1[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields1[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
